name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # Keep running other jobs even if one fails
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        openpyxl-version: ['openpyxl==3.0.6', 'openpyxl'] # without version is latest
        formulas-version: ['formulas==1.2.7', 'formulas']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install pytest ${{ matrix.openpyxl-version }} ${{ matrix.formulas-version }}
          pip install -e .

      - name: Display installed versions
        # Useful for debugging which versions actually got installed
        run: pip freeze

      - name: Run tests
        run: pytest